# Generated by Django 2.1.7 on 2024-08-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
            ],
            options={
                'db_table': 'KeyModel',
            },
        ),
        migrations.CreateModel(
            name='ownerreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('status', models.CharField(default='Deactivated', max_length=100)),
            ],
            options={
                'db_table': 'ownerreg',
            },
        ),
        migrations.CreateModel(
            name='uploadfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerid', models.CharField(max_length=100)),
                ('ownername', models.CharField(max_length=100)),
                ('owneremail', models.CharField(max_length=100)),
                ('filedataname', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('filekey', models.CharField(max_length=50)),
                ('filedata', models.BinaryField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'uploadfile',
            },
        ),
        migrations.CreateModel(
            name='userreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('status', models.CharField(default='Deactivated', max_length=100)),
            ],
            options={
                'db_table': 'userreg',
            },
        ),
        migrations.CreateModel(
            name='userrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiveremail', models.CharField(max_length=100)),
                ('ownername', models.CharField(max_length=100)),
                ('filekey', models.CharField(max_length=100)),
                ('owneremail', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('filedata', models.BinaryField()),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'userrequest',
            },
        ),
    ]
