# Generated by Django 5.1.6 on 2025-02-17 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.EmailField(max_length=254)),
                ('otp', models.IntegerField(null=True)),
                ('status', models.CharField(default='Pending', max_length=100)),
            ],
            options={
                'db_table': 'RequestFiles',
            },
        ),
        migrations.CreateModel(
            name='TextECCEncryption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader', models.EmailField(max_length=254)),
                ('filename', models.CharField(max_length=100)),
                ('file_path', models.FileField(upload_to='static\\EnTextFiles')),
                ('encrypted_data', models.BinaryField()),
                ('public_key', models.BinaryField()),
                ('private_key', models.BinaryField()),
                ('status', models.CharField(default='Pending', max_length=100)),
            ],
            options={
                'db_table': 'TextECCEncryption',
            },
        ),
        migrations.DeleteModel(
            name='KeyModel',
        ),
        migrations.DeleteModel(
            name='uploadfile',
        ),
        migrations.AlterField(
            model_name='ownerreg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userreg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='requestfiles',
            name='file_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.texteccencryption'),
        ),
    ]
